name: Starter workflow
on:
  - push
  - pull_request
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
      
      - name: Type checking
        run: bun run typecheck
      
      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test

  CD: 
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Build and Deploy
        run: echo "Buid and deploy process here" 
      